# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy
builds:
- env:
    # goreleaser does not work with CGO, it could also complicate
    # usage by users in CI/CD systems like Terraform Cloud where
    # they are unable to install libraries.
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goos:
    # - freebsd
    ### ⨯ release failed after 805.98s error=failed to build for windows_386: # github.com/terraform-providers/terraform-provider-aws/aws
    ### aws/resource_aws_cloudwatch_event_api_destination.go:47:41: constant 9223372036854775807 overflows int
    # - windows
    - linux
    - darwin
  goarch:
    - amd64
    ### ⨯ release failed after 16.61s error=failed to build for linux_386: # github.com/terraform-providers/terraform-provider-aws/aws
    ### aws/resource_aws_cloudwatch_event_api_destination.go:47:41: constant 9223372036854775807 overflows int
    # - '386'
    ### ⨯ release failed after 22.45s error=failed to build for linux_arm_6: # github.com/terraform-providers/terraform-provider-aws/aws
    ### aws/resource_aws_cloudwatch_event_api_destination.go:47:41: constant 9223372036854775807 overflows int
    # - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: '386'
  binary: '{{ .ProjectName }}_v{{ .Version }}'
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      # if you are using this in a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
changelog:
  skip: true



# $ goreleaser release --rm-dist --timeout 60m
#    • releasing...
#    • loading config file       file=.goreleaser.yml
#    • loading environment variables
#    • getting and validating git state
#       • releasing v3.9.2-pre, commit 99e061f79a6a61b19615fe466b90ed7ae09ffb3d
#    • parsing tag
#    • running before hooks
#       • running go mod tidy
#    • setting defaults
#       • snapshotting
#       • github/gitlab/gitea releases
#       • project name
#       • loading go mod information
#       • building binaries
#       • creating source archive
#       • archives
#       • linux packages
#       • snapcraft packages
#       • calculating checksums
#       • signing artifacts
#       • docker images
#       • docker manifests
#       • artifactory
#       • blobs
#       • homebrew tap formula
#       • scoop manifests
#       • twitter
#       • milestones
#    • snapshotting
#    • checking ./dist
#       • --rm-dist is set, cleaning it up
#    • loading go mod information
#    • writing effective config file
#       • writing                   config=dist/config.yaml
